### PR TITLE
[Feature #161037174] initial commit for landing page

### PR DESCRIPTION
**Pull request by Arusey**
**What does this PR do?**
It has the markup and styling for the site's landing and login page
**Descriptions of the tasks to be completed?**
Have a markup for the landing and login page combined with styling configured such that all the elements in the site are responsive
**How should this be manually tested?**
After cloning the repo, cd into it and try to load the index.html file on your browser
**Background context**
The buttons required to display on a small device are invisible therefore lookout for that small error
**Pivotal tracker story**
#161037174
screenshot from 2018-10-08 22-32-47

### CODE REVIEW

**Comment by Arusey** [comment]
Duly noted

**Comment by sharkdevs** [comment]
Kindly format your comments for readability purposes

**Comment by Arusey** [comment]
aye..noted

**Comment by kamaudan** [comment]
Good work, you can reposition the login, for the page to look symetrical.

**Comment by Paulstar200** [comment]
Good design. I have the following concerns though. The logout button in the navbar cannot be present yet we are displaying the login form. And the description too is good but maybe let's find a way to make it look better. Good work though.

**Comment by Arusey** [comment]
> Good design. I have the following concerns though. The logout button in the navbar cannot be present yet we are displaying the login form. And the description too is good but maybe let's find a way to make it look better. Good work though.

Noted

**Comment by Arusey** [comment]
> Good work, you can reposition the login, for the page to look symmetrical.

working on those

**Comment by Krafty-Coder** [comment]
Nice work and neat code... Though you should avoid having commented out code and whitespaces in your styling 
Otherwise you have done well :clap:

**Comment by codeMarble254** [comment]
Great work

**Comment by codeMarble254** [comment]
Just eliminate the logout button from there

**Pull request merged**
